services:
  tts:
    image: spark:latest
    container_name: spark_test
    runtime: nvidia
    ports:
      - "8301:8301"
      - "8302:8302"
      - "8303:8303"
    volumes:
      - ./:/app
      - /data/models/Spark-TTS-0.5B:/models/Spark-TTS-0.5B
    working_dir: /app
    environment:
      ENV: "PROD"
    # command: tail -f /dev/null
    command:  bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate sparktts && jupyter lab --no-browser --port=8301 --ip=0.0.0.0 --allow-root"
