services:
  tts:
    image: spark:latest
    container_name: spark
    runtime: nvidia
    ports:
      - "8301:8301"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      ENV: "PROD"
    # command: tail -f /dev/null
    command:  bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate sparktts && jupyter lab --no-browser --port=8301 --ip=0.0.0.0 --allow-root"